package Mensajes;
public enum TipoMensaje{
    CONEXION,
    CONFIRMAR_CONEXION,
    CERRAR_CONEXION,
    LISTA_USUARIOS,
    CONFIRMACION_LISTA_USUARIOS,
    PEDIR_FICHERO,
    EMITIR_FICHERO,
    PREPARADO_CLIENTE_SERVIDOR,
    CONFIRMACION,
    PREPARADO_SERVIDOR_CLIENTE,
    CONFIRMACION_CERRAR_CONEXION;
}
